target_fps = 60
render_mode = "Ascii"
density_scale = 1.0
color_enabled = true
color_mode = "Direct"
bg_style = "Black"
invert = false
contrast = 2.0
brightness = 0.05
saturation = 1.0
charset_index = 8
charset = " .':;il!i><+?-)(ItfjxnoC00@"
shape_matching = false
edge_threshold = 0.4
edge_mix = 1.0
aspect_ratio = 1.5
audio_sensitivity = 1.5
audio_smoothing = 0.2
glow_intensity = 0.8
fade_decay = 0.15
show_spectrum = true
fullscreen = false
