target_fps = 60
render_mode = "Braille"
density_scale = 1.5
color_enabled = true
color_mode = "Quantized"
bg_style = "SourceDim"
invert = true
contrast = 1.8
brightness = -0.1
saturation = 2.5
charset_index = 6
charset = "@#%&?*+;:,."
shape_matching = false
edge_threshold = 0.0
edge_mix = 0.0
aspect_ratio = 1.5
audio_sensitivity = 3.0
audio_smoothing = 0.1
glow_intensity = 0.0
fade_decay = 0.4
show_spectrum = true
fullscreen = false
